/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.*;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Manu
 */
public class PanelProductos extends javax.swing.JPanel {

    /**
     * Creates new form ventanaBajaProducto
     */
    private VentanaPrincipal ventanaprincipal;
    private DefaultListModel modelo;
    
    public PanelProductos(VentanaPrincipal ventana) {
        
        initComponents();
        this.ventanaprincipal=ventana;
        rellenarLista();
        Image imagen = new ImageIcon("fondoJavapop.png").getImage();
        ImageIcon imgRedim = new ImageIcon(imagen.getScaledInstance(742, 431, Image.SCALE_SMOOTH));
        jLabel9.setIcon(imgRedim);  
    }

    public VentanaPrincipal getVentanaprincipal() {
        return ventanaprincipal;
    }

    public void setVentanaprincipal(VentanaPrincipal ventanaprincipal) {
        this.ventanaprincipal = ventanaprincipal;
    }

    public JList<String> getProductosList() {
        return productosList;
    }

    public void setProductosList(JList<String> productosList) {
        this.productosList = productosList;
    }
    
    /**
     * 
     * Metodo el cual rellena el JList con los productos que tiene el cliente en venta actualmente
     * 
     * 
     */
    
    public void rellenarLista(){
        Cliente cliente = (Cliente)ventanaprincipal.getUsuarioLoggeado();
        //Crear un objeto DefaultListModel
        DefaultListModel listModel = new DefaultListModel();
        //Recorrer el contenido del ArrayList
        for(int i=0; i<cliente.getProductosEnVenta().size(); i++) {
            //Añadir cada elemento del ArrayList en el modelo de la lista
            listModel.add(i, cliente.getProductosEnVenta().get(i).getTitulo());
        }
        //Asociar el modelo de lista al JList
        productosList.setModel(listModel);
        productosList.repaint();
        productosList.updateUI();
    }
    
    
    /**
     * 
     * 
     * 
     * Metodo el cual rellena la informacion del producto en los distintos TextField
     * 
     * 
     * @param producto 
     */
    
    public void rellenarInfo(Producto producto){
        
        tituloTextField1.setText(producto.getTitulo());
        precioTextField1.setText(String.valueOf(producto.getPrecio())+" €");
        estadoTextField.setText(producto.getEstado().toString());
        categoriaTextField.setText(producto.toStringCategoria());
        descripcionTextArea.setText(producto.getDescripcion());
        ImageIcon imagen = producto.getFotografia();
        ImageIcon imgRedim = new ImageIcon(imagen.getImage().getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH));
        jLabel10.setIcon(imgRedim);
                
        this.revalidate();
        this.repaint();
        this.updateUI();
        
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productosList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        categoriaTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tituloTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        precioTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        estadoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(742, 431));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productosList.setBackground(new java.awt.Color(217, 32, 217));
        productosList.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        productosList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        productosList.setSelectionBackground(new java.awt.Color(0, 0, 255));
        productosList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productosListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productosList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 170));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos En Venta");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, -1));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton1.setText("Eliminar Producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 160, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Información del producto");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 180, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Descripción:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 120, -1));

        categoriaTextField.setEditable(false);
        categoriaTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        categoriaTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add(categoriaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 140, 30));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Título:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, 20));

        tituloTextField1.setEditable(false);
        tituloTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        tituloTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add(tituloTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 140, 30));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Precio:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 120, -1));

        precioTextField1.setEditable(false);
        precioTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        precioTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add(precioTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 60, 30));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Estado:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, -1));

        estadoTextField.setEditable(false);
        estadoTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        estadoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        estadoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoTextFieldActionPerformed(evt);
            }
        });
        add(estadoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 140, 30));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Categoría:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 120, -1));

        descripcionTextArea.setEditable(false);
        descripcionTextArea.setColumns(20);
        descripcionTextArea.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        descripcionTextArea.setLineWrap(true);
        descripcionTextArea.setRows(5);
        descripcionTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(descripcionTextArea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 170, 80));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TUS PRODUCTOS");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 250, -1));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton2.setText("Añadir Producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 150, -1));

        jLabel10.setText("jLabel10");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 200, 130));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Imagen del Producto");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 200, -1));

        jLabel9.setText("AÑADIR FONDO");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 742, 431));
    }// </editor-fold>//GEN-END:initComponents

    private void productosListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productosListMouseClicked
        Cliente cliente = (Cliente) ventanaprincipal.getUsuarioLoggeado();
        Producto producto = cliente.getProductosUsuario().get(productosList.getSelectedIndex());
        rellenarInfo(producto);
    }//GEN-LAST:event_productosListMouseClicked

    private void estadoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Cliente cliente = (Cliente)ventanaprincipal.getUsuarioLoggeado();
            String botones[]={"Sí","No"};
            if(productosList.getSelectedValue()==null){
                JOptionPane.showMessageDialog(null,"No ha seleccionado ningún producto", "Error!", JOptionPane.ERROR_MESSAGE);
            }else{
                int eleccion = JOptionPane.showOptionDialog(this, "¿Desea eliminarlo?", "Informacion", 0,0,null,botones,null);         
                if(eleccion == JOptionPane.YES_OPTION){
                    for(Producto cadaProducto : cliente.getProductosEnVenta()){
                        if(cadaProducto.getTitulo().equals(productosList.getSelectedValue())){
                            cliente.eliminarProductoCliente(cadaProducto);
                            cliente.guardarProductosEnVenta();
                            UtilidadJavaPop.guardarProductos();
                            tituloTextField1.setText("");
                            descripcionTextArea.setText("");
                            precioTextField1.setText("");
                            categoriaTextField.setText("");
                            estadoTextField.setText("");
                            rellenarLista();
                            this.revalidate();
                            this.repaint();
                            this.updateUI();
                            break;

                        }
                    }
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaAltaProductos ventanaDeProductos = new VentanaAltaProductos(this.getVentanaprincipal(),this,true);
        ventanaDeProductos.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField categoriaTextField;
    private javax.swing.JTextArea descripcionTextArea;
    private javax.swing.JTextField estadoTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField precioTextField1;
    private javax.swing.JList<String> productosList;
    private javax.swing.JTextField tituloTextField1;
    // End of variables declaration//GEN-END:variables
}
