/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Cliente;
import clases.Usuario;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Manu
 */
public class PanelInicial extends javax.swing.JPanel {
    
    
    private VentanaPrincipal ventanaPrincipal;

    /**
     * Creates new form panelInicial
     * @param usuario
     */
    
    
    public PanelInicial(VentanaPrincipal ventana) {
        initComponents();
        this.setVisible(true);
        this.ventanaPrincipal = ventana;
        if(ventana.getUsuarioLoggeado().isAdmin()){
           usuarioLabel.setText("Bienvenido Admin");
            
        }else{
            Cliente cliente = (Cliente) ventana.getUsuarioLoggeado();
            usuarioLabel.setText("Bienvenido, "+cliente.getNombre());
        }
        //Image imagen = new ImageIcon(".\\src\\main\\java\\Imagenes\\javapop.png").getImage();
        Image imagen = new ImageIcon("fondoJavapop.png").getImage();
        ImageIcon imgRedim = new ImageIcon(imagen.getScaledInstance(742, 431, Image.SCALE_SMOOTH));
        jLabel1.setIcon(imgRedim);
        this.updateUI();
        this.revalidate();
        this.repaint();
    }
    

    public VentanaPrincipal getVentanaPrincipal() {
        return ventanaPrincipal;
    }

    public void setVentanaPrincipal(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        usuarioLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton1.setText("Cerrar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 140, 48));

        usuarioLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        usuarioLabel.setForeground(new java.awt.Color(51, 255, 204));
        usuarioLabel.setText("nombre Usuario");
        add(usuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, 730, 36));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Proyecto realizado por José Manuel Fando Álamo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 400, -1));

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 430));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ventanaPrincipal.setVisible(false);
        ventanaPrincipal.setUsuarioLoggeado(null);
        VentanaLogIn logIn = new VentanaLogIn(ventanaPrincipal);
        ventanaPrincipal.getMenuAdmin().setVisible(true);
        ventanaPrincipal.getMenuCliente().setVisible(true);
        logIn.setVisible(true);
        ventanaPrincipal.getPanelPrincipal().add(new PanelInicial(ventanaPrincipal));
        ventanaPrincipal.getPanelPrincipal().revalidate();
        ventanaPrincipal.getPanelPrincipal().repaint();
        ventanaPrincipal.getPanelPrincipal().updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
