/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.*;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Manu
 */
public class PanelMiPerfil extends javax.swing.JPanel {

    /**
     * Creates new form PanelMiPerfil
     */
    private VentanaPrincipal ventanaPrincipal;
    
    
    public PanelMiPerfil(VentanaPrincipal ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
        rellenarInfo();
        Image imagen = new ImageIcon("fondoJavapop.png").getImage();
        ImageIcon imgRedim = new ImageIcon(imagen.getScaledInstance(742, 431, Image.SCALE_SMOOTH));
        jLabel13.setIcon(imgRedim);  
    }

    public VentanaPrincipal getVentanaPrincipal() {
        return ventanaPrincipal;
    }

    public void setVentanaPrincipal(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
    }
    
    
    /**
     * 
     * 
     * Metodo el cual rellena la informacion del usuario Loggeado
     * 
     */
    public void rellenarInfo(){
        Usuario usuario = ventanaPrincipal.getUsuarioLoggeado();
        correoTextField.setText(usuario.getCorreo());
        clientePanel.setVisible(false);
        clienteProfPanel.setVisible(false);
        hacerseProfPanel.setVisible(false);
        if(!usuario.isAdmin()){
            hacerseProfPanel.setVisible(true);
            Cliente cliente = (Cliente) usuario;
            clientePanel.setVisible(true);
            dniTextField.setText(cliente.getDni());
            nombreTextField.setText(cliente.getNombre());
            ubicacionTextField.setText(cliente.getUbicacion().getCiudad()+", "+cliente.getUbicacion().getCodigoPostal());
            tarjetaTextField.setText(cliente.getTarjetaCredito());
            if(usuario.getClass().equals(ClienteProfesional.class)){
                hacerseProfPanel.setVisible(false);
                ClienteProfesional clienteProf = (ClienteProfesional) cliente;
                clienteProfPanel.setVisible(true);
                descripcionTextArea.setText(clienteProf.getDescripion());
                telefonoTextField.setText(String.valueOf(clienteProf.getTelefono()));
                horarioTextField.setText(clienteProf.getHorario());
                webTextField.setText(clienteProf.getWeb());
            }
        this.revalidate();
        this.repaint();
        this.updateUI();
           
        }  
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        correoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        clientePanel = new javax.swing.JPanel();
        tarjetaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        dniTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ubicacionTextField = new javax.swing.JTextField();
        clienteProfPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        horarioTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        telefonoTextField = new javax.swing.JTextField();
        webTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hacerseProfPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(742, 431));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        correoTextField.setEditable(false);
        correoTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        correoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add(correoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 160, 30));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Correo:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 100, 30));

        clientePanel.setBackground(new java.awt.Color(153, 153, 153));
        clientePanel.setForeground(new java.awt.Color(102, 102, 102));
        clientePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tarjetaTextField.setEditable(false);
        tarjetaTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        tarjetaTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientePanel.add(tarjetaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, 30));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tarjeta:");
        clientePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 160, 140, 30));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Ubicación: ");
        clientePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 30));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre:");
        clientePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 30));

        nombreTextField.setEditable(false);
        nombreTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        nombreTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientePanel.add(nombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 100, 30));

        dniTextField.setEditable(false);
        dniTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        dniTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientePanel.add(dniTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 30));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("DNI:");
        clientePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        ubicacionTextField.setEditable(false);
        ubicacionTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        ubicacionTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientePanel.add(ubicacionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, 30));

        add(clientePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 310, 200));

        clienteProfPanel.setBackground(new java.awt.Color(153, 153, 153));
        clienteProfPanel.setForeground(new java.awt.Color(102, 102, 102));
        clienteProfPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Descripción:");
        clienteProfPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 30));

        descripcionTextArea.setEditable(false);
        descripcionTextArea.setColumns(20);
        descripcionTextArea.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        descripcionTextArea.setLineWrap(true);
        descripcionTextArea.setRows(5);
        jScrollPane2.setViewportView(descripcionTextArea);

        clienteProfPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 150, 60));

        horarioTextField.setEditable(false);
        horarioTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        horarioTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clienteProfPanel.add(horarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 150, 30));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Horario:");
        clienteProfPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 30));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Télefono:");
        clienteProfPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 30));

        telefonoTextField.setEditable(false);
        telefonoTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        telefonoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clienteProfPanel.add(telefonoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 150, 30));

        webTextField.setEditable(false);
        webTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        webTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clienteProfPanel.add(webTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 150, 30));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Web:");
        clienteProfPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, 30));

        add(clienteProfPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 280, 250));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mi Perfil");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 200, 30));

        hacerseProfPanel.setBackground(new java.awt.Color(153, 153, 153));
        hacerseProfPanel.setForeground(new java.awt.Color(153, 153, 153));
        hacerseProfPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Conviertete en Profesional!!");
        hacerseProfPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 200, 30));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton1.setText("Cliente Profesional");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        hacerseProfPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 200, -1));

        jLabel12.setForeground(new java.awt.Color(102, 255, 204));
        jLabel12.setText("-->");
        hacerseProfPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 30, 30));

        add(hacerseProfPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 460, 40));

        jLabel13.setText("AÑADIR FONDO");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 742, 431));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaHacerseProfesional ventana = new VentanaHacerseProfesional(ventanaPrincipal,this, true);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel clientePanel;
    private javax.swing.JPanel clienteProfPanel;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JTextArea descripcionTextArea;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JPanel hacerseProfPanel;
    private javax.swing.JTextField horarioTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField tarjetaTextField;
    private javax.swing.JTextField telefonoTextField;
    private javax.swing.JTextField ubicacionTextField;
    private javax.swing.JTextField webTextField;
    // End of variables declaration//GEN-END:variables
}
