/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.*;
import java.awt.Image;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.temporal.TemporalQueries;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author Manu
 */
public class PanelVentas extends javax.swing.JPanel {

    /**
     * Creates new form PanelVentas
     */
    private VentanaPrincipal ventanaPrincipal;
    
    
    public PanelVentas(VentanaPrincipal ventanaPrincipal) {
        initComponents();
        this.ventanaPrincipal = ventanaPrincipal;
        if(UtilidadJavaPop.getVentas().size()>0){
               rellenarLista();
        }else{
             JOptionPane.showMessageDialog(null, "No hay ventas registradas", "Error", JOptionPane.ERROR_MESSAGE);
        }
        Image imagen = new ImageIcon("fondoJavapop.png").getImage();
        ImageIcon imgRedim = new ImageIcon(imagen.getScaledInstance(742, 431, Image.SCALE_SMOOTH));
        jLabel10.setIcon(imgRedim);
        Image imagenLupa = new ImageIcon("lupa.png").getImage();
        ImageIcon imgRedimLupa = 
                new ImageIcon(imagenLupa.getScaledInstance(50,50, Image.SCALE_SMOOTH));
        buscarButton.setIcon(imgRedimLupa);
    }

    public JList<String> getVentasList() {
        return ventasList;
    }

    public void setVentasList(JList<String> ventasList) {
        this.ventasList = ventasList;
    }
    public VentanaPrincipal getVentanaPrincipal() {
        return ventanaPrincipal;
    }

    public void setVentanaPrincipal(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
    }

    public LocalDate getFecha() {
        Date fecha = (Date) fechaSpinner.getValue();
        Instant instant = Instant.ofEpochMilli(fecha.getTime());
        LocalDate localDate = LocalDateTime.ofInstant(instant, ZoneId.systemDefault()).toLocalDate();
        return localDate;
    }
        
    /**
     * 
     * Metodo el cual rellena el JList con los datos de todas las ventas realizadas hasta el momento
     * 
     * 
     */   
        
    public void rellenarLista(){
        
        //Crear un objeto DefaultListModel
        DefaultListModel listModel = new DefaultListModel();
        //Recorrer el contenido del ArrayList
        for(int i=0; i<UtilidadJavaPop.getVentas().size(); i++) {
            //Añadir cada elemento del ArrayList en el modelo de la lista
            listModel.add(i, UtilidadJavaPop.getVentas().get(i).getProducto().getTitulo());
        }
        //Asociar el modelo de lista al JList
        ventasList.setModel(listModel);
        ventasList.repaint();
        ventasList.updateUI();
    }   
        
        
    public void rellenarInfo(Venta venta){
        productoTextField.setText(venta.getProducto().getTitulo());
        compradorTextField.setText(venta.getComprador().getCorreo());
        vendedorTextField.setText(venta.getVendedor().getCorreo());
        fechaTextField.setText(venta.getFechaCompra().toString());
        dniCompradorTextField.setText(venta.getComprador().getDni());
        dniVendedorTextField.setText(venta.getVendedor().getDni());
    }
    
    public void vaciar(){
        productoTextField.setText("");
        compradorTextField.setText("");
        vendedorTextField.setText("");
        fechaTextField.setText("");
        dniCompradorTextField.setText("");
        dniVendedorTextField.setText("");
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ventasList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        compradorTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        vendedorTextField = new javax.swing.JTextField();
        dniCompradorTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dniVendedorTextField = new javax.swing.JTextField();
        productoTextField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        fechaSpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel2.setText("AÑADIR FONDO");

        setMaximumSize(new java.awt.Dimension(742, 431));
        setMinimumSize(new java.awt.Dimension(742, 431));
        setPreferredSize(new java.awt.Dimension(742, 431));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VENTAS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 179, 47));

        ventasList.setBackground(new java.awt.Color(255, 18, 233));
        ventasList.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        ventasList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ventasList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventasListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ventasList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, 180));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ventas Totales");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 110, 20));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Fecha:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 160, 30));

        fechaTextField.setEditable(false);
        fechaTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        add(fechaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 130, 30));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Producto:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 110, 30));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Comprador:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 100, 30));

        compradorTextField.setEditable(false);
        compradorTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        add(compradorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 130, 30));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Vendedor:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 110, 30));

        vendedorTextField.setEditable(false);
        vendedorTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        vendedorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendedorTextFieldActionPerformed(evt);
            }
        });
        add(vendedorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 130, 30));

        dniCompradorTextField.setEditable(false);
        dniCompradorTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        add(dniCompradorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 130, 30));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("DNI Comprador:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 160, 30));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("DNI Vendedor:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 140, 30));

        dniVendedorTextField.setEditable(false);
        dniVendedorTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        add(dniVendedorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 130, 30));

        productoTextField.setEditable(false);
        productoTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        add(productoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 130, 30));

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });
        add(buscarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 50, 50));

        fechaSpinner.setModel(new javax.swing.SpinnerDateModel());
        fechaSpinner.setEditor(new javax.swing.JSpinner.DateEditor(fechaSpinner, "dd/MM/yyyy"));
        add(fechaSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 130, 50));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setText("Ver Producto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 150, 90));

        jLabel10.setText("jLabel10");
        jLabel10.setMaximumSize(new java.awt.Dimension(742, 431));
        jLabel10.setMinimumSize(new java.awt.Dimension(742, 431));
        jLabel10.setPreferredSize(new java.awt.Dimension(742, 431));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ventasListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasListMouseClicked
        Venta venta = UtilidadJavaPop.getVentas().get(ventasList.getSelectedIndex());
        vaciar();
        rellenarInfo(venta);
        this.revalidate();
        this.repaint();
        this.updateUI();

    }//GEN-LAST:event_ventasListMouseClicked

    private void vendedorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendedorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendedorTextFieldActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
            vaciar();
            Administrador admin = (Administrador) ventanaPrincipal.getUsuarioLoggeado();
            ArrayList<Venta> ventasFecha=admin.consultaVentas(getFecha());
            if(ventasFecha.size()>0){
                
                //Crear un objeto DefaultListModel
                DefaultListModel listModel = new DefaultListModel();
                //Recorrer el contenido del ArrayList
                for(int i=0; i<ventasFecha.size(); i++) {
                    //Añadir cada elemento del ArrayList en el modelo de la lista
                    listModel.add(i, ventasFecha.get(i).getProducto().getTitulo());
                }
                    //Asociar el modelo de lista al JList
                ventasList.setModel(listModel);
                ventasList.repaint();
                ventasList.updateUI();      
            }else{
                JOptionPane.showMessageDialog(null,"No hay ventas en dicha fecha", "Info", JOptionPane.INFORMATION_MESSAGE);
            }


    }//GEN-LAST:event_buscarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!ventasList.isSelectionEmpty()){
            VentanaInfoProducto ventana = new VentanaInfoProducto(this);
            ventana.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null,"No ha seleccionado niguna venta", "Info", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField compradorTextField;
    private javax.swing.JTextField dniCompradorTextField;
    private javax.swing.JTextField dniVendedorTextField;
    private javax.swing.JSpinner fechaSpinner;
    private javax.swing.JTextField fechaTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField productoTextField;
    private javax.swing.JTextField vendedorTextField;
    private javax.swing.JList<String> ventasList;
    // End of variables declaration//GEN-END:variables
}
