/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.*;
import java.awt.Image;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Manu
 */
public class PanelConsultaUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form panelConsultaUsuarios
     */
    private VentanaPrincipal ventanaPrincipal;
    
    
    public PanelConsultaUsuarios(VentanaPrincipal ventanaPrincipal) {
        initComponents();
        rellenarLista();
        this.ventanaPrincipal = ventanaPrincipal;
        Image imagen = new ImageIcon("fondoJavapop.png").getImage();
        ImageIcon imgRedim = new ImageIcon(imagen.getScaledInstance(742, 431, Image.SCALE_SMOOTH));
        jLabel11.setIcon(imgRedim);  
       
    }

    public VentanaPrincipal getVentanaPrincipal() {
        return ventanaPrincipal;
    }

    public void setVentanaPrincipal(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
    }
    
    
    
    
    
    /**
     * 
     * Metodo el cual rellena el JList con los datos de todos los usuarios registrados
     * 
     * 
     */
    public void rellenarLista(){
        
        //Crear un objeto DefaultListModel
        DefaultListModel listModel = new DefaultListModel();
        //Recorrer el contenido del ArrayList
        for(int i=0; i<UtilidadJavaPop.getUsuarios().size(); i++) {
            //Añadir cada elemento del ArrayList en el modelo de la lista
            listModel.add(i, UtilidadJavaPop.getUsuarios().get(i).getCorreo());
        }
        //Asociar el modelo de lista al JList
        usuariosList.setModel(listModel);
        usuariosList.repaint();
        usuariosList.updateUI();
    }
    
    
    /**
     * 
     * Metodo el cual vacia toda la informacion actual de los TextField
     * 
     * 
     * 
     */
    public void vaciar(){
        correoTextField.setText("");
        dniTextField.setText("");
        descripcionTextArea.setText("");
        telefonoTextField.setText("");
        horarioTextField.setText("");
        nombreTextField.setText("");
        ubicacionTextField.setText("");
        webTextField.setText("");
        tarjetaTextField.setText("");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        correoTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tipoClienteLabel = new javax.swing.JLabel();
        clientePanel = new javax.swing.JPanel();
        tarjetaTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        dniTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ubicacionTextField = new javax.swing.JTextField();
        clienteProfPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        horarioTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        telefonoTextField = new javax.swing.JTextField();
        webTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bajaClienteButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(742, 431));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuariosList.setBackground(new java.awt.Color(255, 27, 236));
        usuariosList.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        usuariosList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        usuariosList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuariosListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usuariosList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, 200));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USUARIOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 211, 30));

        correoTextField.setEditable(false);
        correoTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        correoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add(correoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 160, 30));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Correo:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 100, 30));

        tipoClienteLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tipoClienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(tipoClienteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 130, 20));

        clientePanel.setBackground(new java.awt.Color(153, 153, 153));
        clientePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tarjetaTextField.setEditable(false);
        tarjetaTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        tarjetaTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientePanel.add(tarjetaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, 30));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tarjeta Crédito:");
        clientePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 160, 130, 30));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Ubicación: ");
        clientePanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 30));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre:");
        clientePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 30));

        nombreTextField.setEditable(false);
        nombreTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        nombreTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientePanel.add(nombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 100, 30));

        dniTextField.setEditable(false);
        dniTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        dniTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientePanel.add(dniTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 30));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("DNI:");
        clientePanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        ubicacionTextField.setEditable(false);
        ubicacionTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        ubicacionTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clientePanel.add(ubicacionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 160, 30));

        add(clientePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 300, 200));

        clienteProfPanel.setBackground(new java.awt.Color(153, 153, 153));
        clienteProfPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Descripción:");
        clienteProfPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 100, 30));

        descripcionTextArea.setEditable(false);
        descripcionTextArea.setColumns(20);
        descripcionTextArea.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        descripcionTextArea.setLineWrap(true);
        descripcionTextArea.setRows(5);
        descripcionTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(descripcionTextArea);

        clienteProfPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 150, 60));

        horarioTextField.setEditable(false);
        horarioTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        horarioTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clienteProfPanel.add(horarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 150, 30));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Horario:");
        clienteProfPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 30));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Télefono:");
        clienteProfPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 30));

        telefonoTextField.setEditable(false);
        telefonoTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        telefonoTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clienteProfPanel.add(telefonoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 150, 30));

        webTextField.setEditable(false);
        webTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        webTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        clienteProfPanel.add(webTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 150, 30));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Web:");
        clienteProfPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 30));

        add(clienteProfPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 250, 250));

        bajaClienteButton.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        bajaClienteButton.setText("Baja Usuario");
        bajaClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaClienteButtonActionPerformed(evt);
            }
        });
        add(bajaClienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 200, 30));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Usuarios Registrados");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, -1));

        jLabel11.setText("AÑADIR FONDO");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 742, 431));
    }// </editor-fold>//GEN-END:initComponents

    private void usuariosListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosListMouseClicked
        
        Usuario usuarioExt = null;
        for(Usuario cadaUsuario : UtilidadJavaPop.getUsuarios()){
            if(cadaUsuario.getCorreo().equals(usuariosList.getSelectedValue())){
                usuarioExt = cadaUsuario;
                
            }
            
        }
        vaciar();
        correoTextField.setText(usuarioExt.getCorreo());
        clientePanel.setVisible(false);
        clienteProfPanel.setVisible(false);
        if(!usuarioExt.isAdmin()){
            Cliente cliente =(Cliente)usuarioExt;
            dniTextField.setText(cliente.getDni());
            nombreTextField.setText(cliente.getNombre());
            ubicacionTextField.setText(cliente.getUbicacion().getCiudad()+
                    ", "+cliente.getUbicacion().getCodigoPostal());
            tarjetaTextField.setText(cliente.getTarjetaCredito());
            clientePanel.setVisible(true);
            if(usuarioExt.getClass().equals(ClienteProfesional.class)){
                ClienteProfesional clienteProf = (ClienteProfesional) cliente;
                descripcionTextArea.setText(clienteProf.getDescripion());
                telefonoTextField.setText(String.valueOf(clienteProf.getTelefono()));
                webTextField.setText(clienteProf.getWeb());
                horarioTextField.setText(clienteProf.getHorario());
                clienteProfPanel.setVisible(true);
            }
                
        }
        tipoClienteLabel.setText(usuarioExt.getClass().getSimpleName());
        this.repaint();
        this.revalidate();
        this.updateUI();
        
        
        
        
        
        
        
    }//GEN-LAST:event_usuariosListMouseClicked

    private void bajaClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaClienteButtonActionPerformed
        try{
            String botones[]={"Sí","No"};
            if(usuariosList.getSelectedValue()==null){
                JOptionPane.showMessageDialog(null,"No ha seleccionado ningún usuario", "Error!", JOptionPane.ERROR_MESSAGE);
            }else{
                Administrador admin = (Administrador) ventanaPrincipal.getUsuarioLoggeado();
                if(usuariosList.getSelectedValue().equals(admin.getCorreo())){
                    JOptionPane.showMessageDialog(null,"No puede eliminar al Administrador", "Error!", JOptionPane.ERROR_MESSAGE);
                }else{
                    int eleccion = JOptionPane.showOptionDialog(this, "¿Desea eliminarlo?", "Informacion", 0,0,null,botones,null);         
                    if(eleccion == JOptionPane.YES_OPTION){
                        admin.bajaCliente(correoTextField.getText());
                        UtilidadJavaPop.guardarUsuarios();
                        UtilidadJavaPop.guardarProductos();
                        correoTextField.setText("");
                        descripcionTextArea.setText("");
                        dniTextField.setText("");
                        telefonoTextField.setText("");
                        nombreTextField.setText("");
                        ubicacionTextField.setText("");
                        tarjetaTextField.setText("");
                        horarioTextField.setText("");
                        webTextField.setText("");
                        rellenarLista();
                        this.revalidate();
                        this.repaint();
                        this.updateUI();
                    }
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bajaClienteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bajaClienteButton;
    private javax.swing.JPanel clientePanel;
    private javax.swing.JPanel clienteProfPanel;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JTextArea descripcionTextArea;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JTextField horarioTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField tarjetaTextField;
    private javax.swing.JTextField telefonoTextField;
    private javax.swing.JLabel tipoClienteLabel;
    private javax.swing.JTextField ubicacionTextField;
    private javax.swing.JList<String> usuariosList;
    private javax.swing.JTextField webTextField;
    // End of variables declaration//GEN-END:variables
}
