/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.*;
import static clases.UtilidadJavaPop.registrarCliente;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Manu
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    
    private VentanaLogIn ventanaLogIn;
    
    public Registrarse(VentanaLogIn ventanaLogIn) {
        initComponents();
        clienteprofPanel.setVisible(false);
        this.ventanaLogIn=ventanaLogIn;
        Image imagen = new ImageIcon("fondoJavapop.png").getImage();
        ImageIcon imgRedim = new ImageIcon(imagen.getScaledInstance(jLabel13.getWidth(),jLabel13.getHeight(), Image.SCALE_SMOOTH));
        jLabel13.setIcon(imgRedim);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("logo.png"));
    }
    
    
    /**
     * 
     * 
     * 
     * Metodo el cual crea un cliente normal con los datos introducidos en los diferentes TextField
     * 
     * 
     * 
     * @param correo
     * @param contraseña
     * @param dni
     * @param nombre
     * @param codigopostal
     * @param ciudad
     * @param tarjetaCredito 
     */
    
    public void RegistroCliente(String correo, String contraseña, String dni,String nombre,
            String codigopostal,String ciudad,String tarjetaCredito){
        try{
        Usuario cliente = new Cliente(correo,contraseña,dni,nombre,
            codigopostal,ciudad,tarjetaCredito);
        UtilidadJavaPop.registrarCliente(cliente);
        UtilidadJavaPop.guardarUsuarios();
        this.setVisible(false);
        this.ventanaLogIn.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
           
        }
        
    }
        
        
    /**
     * 
     * Metodo el cual crea un clienteProfesional con los datos introducidos en los diferentes TextField
     * 
     * 
     * 
     * @param correo
     * @param contraseña
     * @param dni
     * @param nombre
     * @param codigopostal
     * @param ciudad
     * @param tarjetacredito
     * @param descripcion
     * @param telefono
     * @param horario
     * @param web 
     */
    public void RegistroClienteProf(String correo, String contraseña, String dni, String nombre, 
            String codigopostal, String ciudad, String tarjetacredito, String descripcion, 
            int telefono,String horario ,String web) {
       try{ 
        Usuario clienteprof = new ClienteProfesional(correo, contraseña, dni, nombre,
                codigopostal, ciudad, tarjetacredito, descripcion, telefono, horario, web);
        
        registrarCliente(clienteprof);
        UtilidadJavaPop.guardarUsuarios();
        this.setVisible(false);
        ventanaLogIn.setVisible(true);
       }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
           
        }
    }

    public VentanaLogIn getVentanaLogIn() {
        return ventanaLogIn;
    }

    public void setVentanaLogIn(VentanaLogIn ventanaLogIn) {
        this.ventanaLogIn = ventanaLogIn;
    }

    
       
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        ciudadTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dniTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contraseñaTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        correoTextField = new javax.swing.JTextField();
        tarjetaTextField = new javax.swing.JTextField();
        postalTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        clienteprofCheck = new javax.swing.JCheckBox();
        clienteprofPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        telfTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        webTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        horarioTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Javapop");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerrar(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Codigo Postal:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 134, 45));

        ciudadTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(ciudadTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 149, 33));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Correo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 134, 33));

        dniTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        dniTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dniTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 149, 33));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Ciudad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 134, 45));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 134, 45));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nombre:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 134, 45));

        contraseñaTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        contraseñaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(contraseñaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 149, 33));

        nombreTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(nombreTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 149, 33));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 255, 204));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tarjeta:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 400, 180, 45));

        correoTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(correoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 149, 33));

        tarjetaTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(tarjetaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 149, 33));

        postalTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(postalTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 149, 36));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("DNI:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 134, 45));

        clienteprofCheck.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        clienteprofCheck.setForeground(new java.awt.Color(102, 255, 204));
        clienteprofCheck.setText("¿Desea ser Cliente Profesional?");
        clienteprofCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteprofCheckActionPerformed(evt);
            }
        });
        getContentPane().add(clienteprofCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 325, -1));

        clienteprofPanel.setBackground(new java.awt.Color(102, 102, 102));
        clienteprofPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Teléfono:");
        clienteprofPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 131, 20));

        telfTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        clienteprofPanel.add(telfTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 249, 29));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Web:");
        clienteprofPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 131, 30));

        webTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        clienteprofPanel.add(webTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 249, 37));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Horario:");
        clienteprofPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 131, 36));

        horarioTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        clienteprofPanel.add(horarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 249, 36));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Descripcion:");
        clienteprofPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 131, 34));

        descripcionTextArea.setColumns(20);
        descripcionTextArea.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        descripcionTextArea.setLineWrap(true);
        descripcionTextArea.setRows(5);
        descripcionTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descripcionTextArea);

        clienteprofPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 249, -1));

        getContentPane().add(clienteprofPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 440, 350));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("REGISTRO");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 308, 40));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton1.setText("Registrarse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 221, 40));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("AÑADIR FONDO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clienteprofCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteprofCheckActionPerformed
        if(clienteprofCheck.isSelected()){
            clienteprofPanel.setVisible(true);
        }else{
            clienteprofPanel.setVisible(false);
        }
        clienteprofPanel.updateUI();
    }//GEN-LAST:event_clienteprofCheckActionPerformed

    private void dniTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTextFieldActionPerformed

    private void contraseñaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraseñaTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        
        
        
        
        
        if(clienteprofCheck.isSelected()){
            RegistroClienteProf(correoTextField.getText(), contraseñaTextField.getText(), 
                dniTextField.getText(), nombreTextField.getText(), postalTextField.getText(), 
                ciudadTextField.getText(), tarjetaTextField.getText(), descripcionTextArea.getText(),Integer.parseInt(telfTextField.getText()),
                horarioTextField.getText(), webTextField.getText());
        }else{
        RegistroCliente(correoTextField.getText(), contraseñaTextField.getText(), 
                dniTextField.getText(), nombreTextField.getText(), postalTextField.getText(), 
                ciudadTextField.getText(), tarjetaTextField.getText());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cerrar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrar
        ventanaLogIn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrar

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ciudadTextField;
    private javax.swing.JCheckBox clienteprofCheck;
    private javax.swing.JPanel clienteprofPanel;
    private javax.swing.JTextField contraseñaTextField;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JTextArea descripcionTextArea;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JTextField horarioTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField postalTextField;
    private javax.swing.JTextField tarjetaTextField;
    private javax.swing.JTextField telfTextField;
    private javax.swing.JTextField webTextField;
    // End of variables declaration//GEN-END:variables
}
