/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.Cliente;
import clases.Usuario;
import clases.UtilidadJavaPop;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Manu
 */
public class VentanaLogIn extends javax.swing.JFrame {
    
    private VentanaPrincipal ventanaPrincipal;

    /**
     * Creates new form ventanaPrincipal
     * @param ventana
     */
    public VentanaLogIn(VentanaPrincipal ventana) {
       initComponents();
       this.ventanaPrincipal=ventana;
       Image imagen = new ImageIcon("fondoJavapop.png").getImage();
       ImageIcon imgRedim = new ImageIcon(imagen.getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(), Image.SCALE_SMOOTH));
       jLabel2.setIcon(imgRedim);
       this.setIconImage(Toolkit.getDefaultToolkit().getImage("logo.png"));
  
    }

        public VentanaPrincipal getVentanaPrincipal() {
            return ventanaPrincipal;
        }

        public void setVentanaPrincipal(VentanaPrincipal ventanaPrincipal) {
            this.ventanaPrincipal = ventanaPrincipal;
        }



    
    
    
    /**
     * 
     * Metodo el cual comprueba los credenciales introducidos y si son correctos nos devuelve el usuario que ha
     * iniciado sesion
     * 
     * 
     * 
     * @param correo
     * @param contraseña
     * @return 
     */
    
    public Usuario LogIn(String correo,String contraseña){ 
        if(correo.equals("admin@javapop.com") && contraseña.equals("admin")){
            for(Usuario cadaUsuario: UtilidadJavaPop.getUsuarios()){
                if(cadaUsuario.isAdmin()){
                    JOptionPane.showMessageDialog(null, 
                            "Bienvenido de nuevo administrador!","Bienvenido",JOptionPane.INFORMATION_MESSAGE);
                    return cadaUsuario;
                }
            }      
        }else{
            for(Usuario cadaUsuario : UtilidadJavaPop.getUsuarios()){
                if(cadaUsuario.getCorreo().equals(correo) && cadaUsuario.getContraseña().equals(contraseña) &&
                        !cadaUsuario.isAdmin()){
                    JOptionPane.showMessageDialog(null, 
                            "Ha iniciado sesion correctamente","Bienvenido",JOptionPane.INFORMATION_MESSAGE);
                    return cadaUsuario;
                }                
            }
        }
        JOptionPane.showMessageDialog(null, "Correo y/o contraseña incorrectos", "Error de registro", JOptionPane.WARNING_MESSAGE);
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        logInButton = new javax.swing.JButton();
        registrarseButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        correoTextField = new javax.swing.JTextField();
        contraseñaLabel = new javax.swing.JLabel();
        contraseñaTextField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Javapop");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(0, 255, 255));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("¡Bienvenido!");
        getContentPane().add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        logInButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        logInButton.setText("Iniciar sesion");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        registrarseButton.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        registrarseButton.setText("Registrarse");
        registrarseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registrarseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Si no se encuetra registrado, registrese aquí!! -->");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 284, 380, 20));

        correoLabel.setBackground(new java.awt.Color(204, 204, 204));
        correoLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        correoLabel.setForeground(new java.awt.Color(51, 255, 204));
        correoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        correoLabel.setText("Correo:");
        getContentPane().add(correoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 30));

        correoTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(correoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 170, 30));

        contraseñaLabel.setBackground(new java.awt.Color(204, 204, 204));
        contraseñaLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        contraseñaLabel.setForeground(new java.awt.Color(51, 255, 204));
        contraseñaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        contraseñaLabel.setText("Contraseña:");
        getContentPane().add(contraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 30));

        contraseñaTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        contraseñaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(contraseñaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 170, 30));

        jLabel2.setText("AÑADIR FONDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrarseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseButtonActionPerformed
        correoTextField.setText("");
        contraseñaTextField.setText("");
        this.setVisible(false);
        JFrame registro =new Registrarse(this);
        registro.setVisible(true);
    }//GEN-LAST:event_registrarseButtonActionPerformed

    
    
    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        char [] arrayC = contraseñaTextField.getPassword();
        String password = new String(arrayC);
        
        
        Usuario usuario =  LogIn(correoTextField.getText(), password);
        
        if(!usuario.isAdmin()){
            Cliente cliente=(Cliente)usuario;
            cliente.cargarProductosComprados();
            cliente.cargarProductosVendidos();
            cliente.cargarProductosEnVenta();
            this.ventanaPrincipal.getMenuAdmin().setVisible(false);
            this.ventanaPrincipal.setVisible(true);
            this.ventanaPrincipal.setUsuarioLoggeado(usuario);
            ventanaPrincipal.getPanelPrincipal().removeAll();
            ventanaPrincipal.getPanelPrincipal().add(new PanelInicial(this.ventanaPrincipal));
            ventanaPrincipal.getPanelPrincipal().revalidate();
            ventanaPrincipal.getPanelPrincipal().repaint();
            ventanaPrincipal.getPanelPrincipal().updateUI();
            this.dispose();
        }else{
           this.ventanaPrincipal.getMenuCliente().setVisible(false);
           this.ventanaPrincipal.setVisible(true);
           this.ventanaPrincipal.setUsuarioLoggeado(usuario);
           ventanaPrincipal.getPanelPrincipal().removeAll();
           ventanaPrincipal.getPanelPrincipal().add(new PanelInicial(this.ventanaPrincipal));
           ventanaPrincipal.getPanelPrincipal().revalidate();
           ventanaPrincipal.getPanelPrincipal().repaint();
           ventanaPrincipal.getPanelPrincipal().updateUI();
           this.dispose();
        } 
    }//GEN-LAST:event_logInButtonActionPerformed

    private void contraseñaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaTextFieldActionPerformed
        
    }//GEN-LAST:event_contraseñaTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseñaLabel;
    private javax.swing.JPasswordField contraseñaTextField;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JTextField correoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logInButton;
    private javax.swing.JButton registrarseButton;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
