/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Manu
 */
public class VentanaAltaProductos extends javax.swing.JDialog {
    
    
     private PanelProductos panelProductos;
     private VentanaPrincipal ventanaPrincipal;
     private ImageIcon imagenProducto;
     private String nombreImagen, rutaImagen, extension = "png";
     private File file;
     private BufferedImage bimage;

    /**
    /**
     * Creates new form VentanaProductos
     * @param parent
     * @param modal
     */
    public VentanaAltaProductos(java.awt.Frame parent,PanelProductos panelProductos, boolean modal) {
        super(parent, modal);
        initComponents();
        this.ventanaPrincipal=(VentanaPrincipal) parent;
        this.panelProductos = panelProductos;
        Image imagen = new ImageIcon("fondoJavapop.png").getImage();
        ImageIcon imgRedim = new ImageIcon(imagen.getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(), Image.SCALE_SMOOTH));
        jLabel2.setIcon(imgRedim);  
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("logo.png"));
    }

    public PanelProductos getPanelProductos() {
        return panelProductos;
    }

    public void setPanelProductos(PanelProductos panelProductos) {
        this.panelProductos = panelProductos;
    }

    public VentanaPrincipal getVentanaPrincipal() {
        return ventanaPrincipal;
    }

    public void setVentanaPrincipal(VentanaPrincipal ventanaPrincipal) {
        this.ventanaPrincipal = ventanaPrincipal;
    }

    public ImageIcon getImagenProducto() {
        return imagenProducto;
    }

    public void setImagenProducto(ImageIcon imagenProducto) {
        this.imagenProducto = imagenProducto;
    }
    
    
    
    

    public Producto.Categoria getCategoria(int posicion){
        switch(posicion){
            case 0:return Producto.Categoria.Moda_y_accesorios;
            case 1:return Producto.Categoria.Tv_audio_y_foto;
            case 2:return Producto.Categoria.Moviles_y_telefonia;
            case 3:return Producto.Categoria.Informatica_y_electronica;
            case 4:return Producto.Categoria.Consolas_y_videojuegos;
            case 5:return Producto.Categoria.Deporte_y_ocio;
    
        }

        return null;
    }
    
    public Producto.Estado getEstado(int estado){
        
        switch(estado){
            case 0:return Producto.Estado.Nuevo;
            case 1:return Producto.Estado.ComoNuevo;
            case 2:return Producto.Estado.Bueno;
            case 3:return Producto.Estado.Aceptable;
            case 4:return Producto.Estado.Regular;
    
        }
        return null;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        añadirButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fotografiaLabel = new javax.swing.JLabel();
        tituloTextField = new javax.swing.JTextField();
        descripcionLabel = new javax.swing.JLabel();
        estadoToolBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        categoriaToolBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        tituloLabel = new javax.swing.JLabel();
        categoriaLabel = new javax.swing.JLabel();
        precioTextField = new javax.swing.JTextField();
        urgenteCheckBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaPop");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        añadirButton.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        añadirButton.setText("Añadir Producto");
        añadirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(añadirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 328, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Precio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 110, 31));

        fotografiaLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        fotografiaLabel.setForeground(new java.awt.Color(51, 255, 204));
        fotografiaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fotografiaLabel.setText("Fotografía:");
        getContentPane().add(fotografiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 180, 110, 20));

        tituloTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        tituloTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(tituloTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 108, 166, 31));

        descripcionLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        descripcionLabel.setForeground(new java.awt.Color(51, 255, 204));
        descripcionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        descripcionLabel.setText("Descripción:");
        getContentPane().add(descripcionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 110, 31));

        estadoToolBox.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        estadoToolBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Como Nuevo", "Bueno", "Aceptable", "Regular" }));
        estadoToolBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoToolBoxActionPerformed(evt);
            }
        });
        getContentPane().add(estadoToolBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 131, 31));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Título:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 110, 31));

        estadoLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        estadoLabel.setForeground(new java.awt.Color(51, 255, 204));
        estadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        estadoLabel.setText("Estado:");
        getContentPane().add(estadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 120, 110, 31));

        categoriaToolBox.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        categoriaToolBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moda y Accesorios", "TV Audio y foto", "Moviles y telefonía", "Informática y Electrónica", "Consolas y Videojuegos", "Deporte y Ocio" }));
        categoriaToolBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaToolBoxActionPerformed(evt);
            }
        });
        getContentPane().add(categoriaToolBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 131, 31));

        descripcionTextArea.setColumns(20);
        descripcionTextArea.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        descripcionTextArea.setLineWrap(true);
        descripcionTextArea.setRows(5);
        descripcionTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descripcionTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 214, -1, 76));

        tituloLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(102, 255, 204));
        tituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLabel.setText("AÑADIR PRODUCTO");
        getContentPane().add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 274, 28));

        categoriaLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        categoriaLabel.setForeground(new java.awt.Color(51, 255, 204));
        categoriaLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoriaLabel.setText("Categoría:");
        getContentPane().add(categoriaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 70, 110, 31));

        precioTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        precioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(precioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 157, 70, 31));

        urgenteCheckBox.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        urgenteCheckBox.setForeground(new java.awt.Color(51, 255, 204));
        urgenteCheckBox.setText("Urgente");
        getContentPane().add(urgenteCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 60, 120, -1));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 140, 80));

        jLabel2.setText("AÑADIR FONDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void añadirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirButtonActionPerformed

        try{
            Cliente cliente = (Cliente) ventanaPrincipal.getUsuarioLoggeado();

            Producto producto = new Producto(tituloTextField.getText(),
                descripcionTextArea.getText(), this.getEstado(estadoToolBox.getSelectedIndex()),
                this.getCategoria(categoriaToolBox.getSelectedIndex()),
                Double.parseDouble(precioTextField.getText()));
            if(this.imagenProducto == null){
                throw new sinImagen();
            }
            
            producto.setFotografia(imagenProducto);
            producto.setUrgente(false);
            if(urgenteCheckBox.isSelected()){
               producto.setUrgente(true);
               LocalDate fechaSubida = LocalDate.now();
               LocalDate fechaCaducidad=fechaSubida.plusDays(7);
               
               JOptionPane.showMessageDialog(null,"Se le ha cargado una cantidad de 5€ a su tarjeta con numero: "
               +cliente.getTarjetaCredito()+", hoy día "
               + fechaSubida+", esta ventaja acabará el día "+ fechaCaducidad,"Producto Urgente",JOptionPane.INFORMATION_MESSAGE);
 
            }
            cliente.añadirProductoCliente(producto);
            cliente.guardarProductosEnVenta();
            UtilidadJavaPop.guardarProductos();
            this.panelProductos.rellenarLista();
            this.dispose();
        }catch(sinImagen sI){
            JOptionPane.showMessageDialog(null,sI.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_añadirButtonActionPerformed

    private void tituloTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloTextFieldActionPerformed

    private void estadoToolBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoToolBoxActionPerformed
        //        // TODO add your handling code here:
    }//GEN-LAST:event_estadoToolBoxActionPerformed

    private void categoriaToolBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaToolBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaToolBoxActionPerformed

    private void precioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.addChoosableFileFilter(new ImageFilter());
        fileChooser.setAcceptAllFileFilterUsed(false);

        int option = fileChooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            rutaImagen = file.getAbsolutePath();
            nombreImagen = file.getName();
            System.out.println("imagen: " + nombreImagen);
        } else {
            JOptionPane.showMessageDialog(this, "Ningún fichero seleccionado", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }
        
        ImageIcon imagenTemporal = new ImageIcon(rutaImagen);
        ImageIcon imgRedimensionada = new ImageIcon(imagenTemporal.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), 1));
        jLabel1.setIcon(imgRedimensionada);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            bimage = ImageIO.read(file);
            File fout = new File(nombreImagen);
            ImageIO.write(bimage, extension, fout);
            imagenProducto = new ImageIcon(rutaImagen);
            JOptionPane.showMessageDialog(this, "Imagen guardada");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar imagen");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    class sinImagen extends Exception{
        public sinImagen(){
            super("No a subido ninguna imganen del producto");
        }
    }
    
    
    
     
    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirButton;
    private javax.swing.JLabel categoriaLabel;
    private javax.swing.JComboBox<String> categoriaToolBox;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JTextArea descripcionTextArea;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JComboBox<String> estadoToolBox;
    private javax.swing.JLabel fotografiaLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField precioTextField;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JTextField tituloTextField;
    private javax.swing.JCheckBox urgenteCheckBox;
    // End of variables declaration//GEN-END:variables
}
