/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JPanel;

/**
 *
 * @author Manu
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaLogIn login = new VentanaLogIn(this);
    private Usuario usuarioLoggeado = null;
    
 
    public Usuario getUsuarioLoggeado() {
        return usuarioLoggeado;
    }

    public void setUsuarioLoggeado(Usuario usuarioLoggeado) {
        this.usuarioLoggeado = usuarioLoggeado;
    }

    public JPanel getPanelPrincipal() {
        return panelPrincipal;
    }

    public void setPanelPrincipal(JPanel panelPrincipal) {
        this.panelPrincipal = panelPrincipal;
    }
    
    

    public VentanaPrincipal() {
        UtilidadJavaPop.añadirAdmin();
        login.setVisible(true);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("logo.png"));
        initComponents();
        UtilidadJavaPop.cargarProductos();
        UtilidadJavaPop.cargarUsuarios();
        UtilidadJavaPop.cargarVentas();
    }



    public JMenuBar getjMenuBar2() {
        return jMenuBar2;
    }

    public void setjMenuBar2(JMenuBar jMenuBar2) {
        this.jMenuBar2 = jMenuBar2;
    }

    public JMenu getMenuAdmin() {
        return menuAdmin;
    }

    public void setMenuAdmin(JMenu menuAdmin) {
        this.menuAdmin = menuAdmin;
    }

    public JMenu getMenuCliente() {
        return menuCliente;
    }

    public void setMenuCliente(JMenu menuCliente) {
        this.menuCliente = menuCliente;
    }
    

    public VentanaLogIn getLogin() {
        return login;
    }

    public void setLogin(VentanaLogIn login) {
        this.login = login;
    }
    
    
    @Override
    public Image getIconImage() {
        
        try {
            Image retValue = Toolkit.getDefaultToolkit().getImage("javapop.png");
            return retValue;
        }
        catch (Exception e) {
            return (null);
        }
    }
  
    
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(false);
            }
         });
        }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        menuAdmin = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuCliente = new javax.swing.JMenu();
        historialProductos = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaPop");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                cerrar(evt);
            }
        });

        panelPrincipal.setLayout(new java.awt.BorderLayout());

        jMenuBar2.setBackground(new java.awt.Color(51, 255, 255));

        jMenu1.setText("Menú Principal");

        jMenuItem8.setText("Ir al Menú Principal");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem10.setText("Mi Perfil");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem9.setText("Cerrar Sesión");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar2.add(jMenu1);

        menuAdmin.setText("Administrador");

        jMenuItem1.setText("Consulta de Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAdmin.add(jMenuItem1);

        jMenuItem2.setText("Consulta de Productos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuAdmin.add(jMenuItem2);

        jMenuItem3.setText("Consulta de Ventas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuAdmin.add(jMenuItem3);

        jMenuBar2.add(menuAdmin);

        menuCliente.setText("Cliente");

        historialProductos.setText("Gestionar tus productos");

        jMenuItem7.setText("Tus Productos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        historialProductos.add(jMenuItem7);

        jMenuItem4.setText("Ver Historial de Productos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        historialProductos.add(jMenuItem4);

        menuCliente.add(historialProductos);

        jMenuItem5.setText("Búsqueda de Producto");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuCliente.add(jMenuItem5);

        jMenuBar2.add(menuCliente);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelConsultaUsuarios(this));
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        panelPrincipal.updateUI();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cerrar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrar
        UtilidadJavaPop.guardarProductos();
        UtilidadJavaPop.guardarUsuarios();
        UtilidadJavaPop.guardarVentas();
        
        if(!usuarioLoggeado.isAdmin()){
            Cliente cliente = (Cliente) usuarioLoggeado;
            cliente.guardarProductosComprados();
            cliente.guardarProductosEnVenta();
            cliente.guardarProductosVendidos();
        }
    }//GEN-LAST:event_cerrar

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelProductos(this));
        panelPrincipal.repaint();
        panelPrincipal.revalidate();
        panelPrincipal.updateUI();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

        this.setVisible(false);
        this.setUsuarioLoggeado(null);
        VentanaLogIn logIn = new VentanaLogIn(this);
        this.getMenuAdmin().setVisible(true);
        this.getMenuCliente().setVisible(true);
        logIn.setVisible(true);
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelInicial(this));
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        panelPrincipal.updateUI();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelInicial(this));
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        panelPrincipal.updateUI();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelMiPerfil(this));
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        panelPrincipal.updateUI();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelConsultaProductos(this));
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        panelPrincipal.updateUI();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelBusqueda(this));
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        panelPrincipal.updateUI();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelVentas(this));
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        panelPrincipal.updateUI();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        panelPrincipal.removeAll();
        panelPrincipal.add(new PanelHistorialProductos(this));
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        panelPrincipal.updateUI();
    }//GEN-LAST:event_jMenuItem4ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu historialProductos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
