/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.*;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Manu
 */
public class VentanaHacerseProfesional extends javax.swing.JDialog {

    
    private Frame ventana;
    private PanelMiPerfil panel;
    
    
    public VentanaHacerseProfesional(java.awt.Frame parent,PanelMiPerfil panel, boolean modal){
        super(parent, modal);
        this.ventana=parent;
        this.panel = panel;
        initComponents();
        
        Image imagen = new ImageIcon("fondoJavapop.png").getImage();
        ImageIcon imgRedim = new ImageIcon(imagen.getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(), Image.SCALE_SMOOTH));
        jLabel2.setIcon(imgRedim);  
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("logo.png"));
    }

    public Frame getVentana() {
        return ventana;
    }

    public void setVentana(VentanaPrincipal ventana) {
        this.ventana = ventana;
    }

    public PanelMiPerfil getPanel() {
        return panel;
    }

    public void setPanel(PanelMiPerfil panel) {
        this.panel = panel;
    }
    

    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionTextArea = new javax.swing.JTextArea();
        horarioTextField = new javax.swing.JTextField();
        webTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        telfTextField = new javax.swing.JTextField();
        profesionalButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaPop");
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hacerse Profesional");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 240, 30));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Horario:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 131, 30));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Descripcion:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 131, 30));

        descripcionTextArea.setColumns(20);
        descripcionTextArea.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        descripcionTextArea.setLineWrap(true);
        descripcionTextArea.setRows(5);
        descripcionTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descripcionTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 249, 70));

        horarioTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(horarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 249, 30));

        webTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(webTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 249, 30));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Web:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 131, 30));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Teléfono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 131, 30));

        telfTextField.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        getContentPane().add(telfTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 130, 30));

        profesionalButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        profesionalButton.setText("Convertirse en Profesional");
        profesionalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesionalButtonActionPerformed(evt);
            }
        });
        getContentPane().add(profesionalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 250, -1));

        jLabel2.setText("AÑADIR FONDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void profesionalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesionalButtonActionPerformed
        
        try{
            VentanaPrincipal ventanaPrincipal = (VentanaPrincipal) ventana;
            Cliente cliente = (Cliente) ventanaPrincipal.getUsuarioLoggeado();
            if(!descripcionTextArea.getText().trim().equals("") && !horarioTextField.getText().trim().equals("") &&
                    !telfTextField.getText().trim().equals("") && !webTextField.getText().trim().equals("")){
                ClienteProfesional clienteProf = UtilidadJavaPop.hacerseProfesional(cliente, descripcionTextArea.getText(),
                        Integer.parseInt(telfTextField.getText())
                        , horarioTextField.getText(), webTextField.getText());
                
                JOptionPane.showMessageDialog(null, "Se le ha cargado una cantidad de 30€ a su tarjeta con número"
                    +clienteProf.getTarjetaCredito(), "Cliente Profesional", JOptionPane.INFORMATION_MESSAGE);
            
            
                ventanaPrincipal.setUsuarioLoggeado(clienteProf);
            }else{
                JOptionPane.showMessageDialog(null, "Algún campo se encuentra vacío", "Error", JOptionPane.ERROR_MESSAGE);
            
            }
            panel.rellenarInfo();
            panel.repaint();
            panel.revalidate();
            panel.updateUI();
            this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_profesionalButtonActionPerformed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descripcionTextArea;
    private javax.swing.JTextField horarioTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton profesionalButton;
    private javax.swing.JTextField telfTextField;
    private javax.swing.JTextField webTextField;
    // End of variables declaration//GEN-END:variables
}
